# Only automatic charging, no option for manual charging
autoCharging: true  # automatically charge drones
autoChargeSafetyMargin: 0.03  # battery remaining when the drone reaches the charger
noCharging: true  # no "charging" group (action)

log_dir: logs/auto_charging
