drones: 8
birds: 80
charger: [22,21]
fields: [
  [3,4,18,19],
  [30,6,45,22],
  [32,35,48,43],
  [4,37,27,44],
]
mapWidth: 50
mapHeight: 50
patrolling: false

birdFieldProbabilities:
  0: [0.6, 0.2, 0.1, 0.1]
  100: [0.1, 0.7, 0.1, 0.1]
  200: [0.1, 0.1, 0.4, 0.4]

droneMovingEnergyConsumption: 0
droneHoveringEnergyConsumption: 0
no_charging: true

log_dir: logs/no_battery
