name: drones
log_dir.append: /drones
adaptation_params:
  config: true
  adapt_every: 10
  prompt_template: prompt_templates.drones.DronesLLMTemplate
  prompt_template_params:
    simulation_description: "You are a coordinator for a smart farm. Your goal is to manage a fleet of drones to protect the fields on the farm against birds. The overall goal is to minimize the damage to the fields."
    extra_goal: ""
    field_attributes:
      threat_level: true
      protecting_drones: true
      necessary_drones_for_full_protection: true
    drone_attributes:
      energy_to_fly_to_charger: false
      battery: true
