name: drones
adaptation_name: adaptations.openai.OpenAIAdaptation
adaptation_params:
  llm: gpt-4o-mini-2024-07-18
  adaptation_steps: 10
  prompt_template: prompt_templates.drones.DronesLLMTemplate
  prompt_template_params:
    extra_goal: ""
