name: groups
log_dir.append: /groups
adaptation_name: adaptations.openai.OpenAIAdaptation
adaptation_params:
  llm: gpt-4o-mini-2024-07-18
  adapt_every: 10
  prompt_template: prompt_templates.groups.GroupsLLMTemplate
  prompt_template_params:
    extra_goal: ""
    field_attributes:
      threat_level: true
      protecting_drones: true
      necessary_drones_for_full_protection: true
    drone_attributes:
      energy_to_fly_to_charger: false
      battery: true
