name: groups_charging
adaptation_name: adaptations.openai.OpenAIAdaptation
adaptation_params:
  llm: gpt-4o-mini-2024-07-18
  adaptation_steps: 10
  prompt_template: prompt_templates.groups.GroupsLLMTemplate
  prompt_template_params:
    extra_goal: Drones with 25% battery or less should be assigned to the "charging" group to reach the charger before running out of battery.
