drones: 10
birds: 100
charger: [22,21]
fields: [
  [3,4,18,19],
  [35,7,50,30],
  [4,37,27,44],
]
mapWidth: 50
mapHeight: 50

name: groups_charging
adaptation_name: adaptations.openai.OpenAIAdaptation
adaptation_params:
  llm: gpt-4o-mini-2024-07-18
  adaptation_steps: 10
  prompt_template: prompt_templates.groups.GroupsLLMTemplate
  prompt_template_params:
    extra_goal: Drones with 25% battery or less should be assigned to the "charging" group to reach the charger before running out of battery.
