name: q_network
adaptation_name: adaptations.rl.q_network_adaptation.QNetworkAdaptation
adaptation_params:
  epsilon: 0.1
  replay_buffer_size: 10_000
  layer_widths: [100, 100]
  batch_size: 64
  learning_rate: 0.001
  gamma: 0.99
  tau: 0.01
  train_every: 1
  target_update_every: 1
  save_path: rl_models/q_network
  config: true
