name.append: _rs
adaptation_params:
  save_path.append: _rs

  reward_shaping:
    reward_state_consistence: 1
    reward_drone_charging: 2
    reward_drone_moving_to_charger: 0.4
    reward_drone_charging_battery: 0.25
    reward_drone_protecting: 1
    reward_drone_moving_to_field: 0.2
    reward_drone_protecting_battery: 0.5