name.append: _threat_level2
log_dir.append: _threat_level2
adaptation_params:
  prompt_template_params:
    extra_goal.append: "\nAlways fully protect the field with the highest threat level. The remaining drones can be idle or assigned to other fields.\n"
