# Allow manual charging, but also provide guard for auto-charging
autoCharging: true  # automatically charge drones
autoChargeSafetyMargin: 0.03  # battery remaining when the drone reaches the charger

log_dir.append: /auto_charging
