name: ppo
log_dir.append: /ppo
adaptation_name: farm.adaptations.rl.ppo_adaptation.PPOAdaptation
adaptation_params:
  adapt_every: 1
  save_path.append: /ppo
  config: true

  batch_size: 64
  epochs: 5
  gamma: 0.97
  trace_lambda: 0.95
  drone_terminated_reward: -10

  common_layer_widths: []
  policy_layer_widths: [100, 100]
  value_layer_widths: [100, 100]
  learning_rate: 0.001
  entropy_regularization: 0.1
  clip_epsilon: 0.2

tensorflow_needed: true
