name.append: _rs2
log_dir.append: _rs2
adaptation_params:
  save_path.append: _rs2

  reward_shaping:
    reward_state_consistence: 1
    reward_drone_charging: 4
    reward_drone_moving_to_charger: 2
    reward_drone_charging_battery: 0.25
    reward_drone_protecting: 2
    reward_drone_moving_to_field: 1
    reward_drone_protecting_battery: 0.5