name.append: _strategy
log_dir.append: _strategy
adaptation_params:
  prompt_template_params:
    strategy: "Always fully protect the field with the highest threat level with the closest drones. Use as many drones as is required for full protection. If the field is already fully protected, keep the drones there to continue protection. The remaining drones can be idle or assigned to other fields."